---
- name: Install nginx WEb Server
  apt: 
    name: nginx 
    state: latest
  
- name: Generate index.html
  template: 
    src: index.j2
    dest: /var/www/html
    mode: 0555
  notify: Restart nginx  

- name: Start WebServers and Enable
  service: 
    name: nginx
    state: started 
    enabled: yes