- name: Create file
  copy:
    dest: /home/vadim/secret/file1.txt
    content:
      Text Line1, in file1 
      Text Line2, in file1
      Text Line3, {{ mytext }}
- name: Create file2
  copy:
    dest: /home/vadim/secret/file2.txt
    content:
      Text Line1, in file2 
      Text Line2, in file2
      Text Line3, {{ mytext }}