- name: Preconfig
  hosts: Test
  tasks:
    - name: Install Docker
      block:
        - name: Add universe distr
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ groovy universe"
            state: present

        - name: Install additional package
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl 
              - gnupg
              - lsb-release
            update-cache: yes
            cache_valid_time: 86400
        - name: Add key Docker
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name:  Install stable repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu groovy stable 
            state: present
            update-cache: yes
            filename: docker
        - name: Install docker-ce 
          apt:
            name: docker.io
            state: latest
            update-cache: yes
        - name: Check install Docker anr reboot
          service:
            name: docker
            state: restarted
            enabled: yes
      become: yes

    - name: Install Docker-compose
      block:
        - name: Get version Compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page

        - name: install Docker-compose
          get_url:
            url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
            dest: /usr/local/bin/docker-compose
            mode: 0755

      become: yes

    - name: Exit install
      block:
      - name: Add user in group Docker
        user:
          name: user
          group: docker
          append: yes
      # - name: Reboot
      #   reboot:
      # become: yes
